vars:
  - dataset: mi

stages:
  transform:
    cmd: python src/transform.py data/${dataset} intermediate/${dataset}/transformed
    deps:
      - data/${dataset}/raw
      - src/transform.py
    params:
      - transform.datasets.${dataset}.shape
    outs:
      - intermediate/${dataset}/transformed
  featurize:
    cmd: python src/featurization.py intermediate/${dataset}/transformed data/${dataset}/labels intermediate/${dataset}/features
    deps:
      - intermediate/${dataset}/transformed
      - data/${dataset}/labels
    params:
      - featurize.level
      - featurize.wavelet
      - featurize.threshold
      - featurize.coefficient_number
    outs:
      - intermediate/${dataset}/features
  train:
    cmd: python src/train.py intermediate/${dataset}/features
    deps:
      - intermediate/${dataset}/features
      - src/train.py
    params:
      - train.state
      - train.split
      - train.svm_kernel
      - train.svm_C
      - train.svm_degree
    outs:
      - model.pkl
  evaluate:
    cmd: python src/evaluate.py model.pkl intermediate/${dataset}/features
    deps:
      - intermediate/${dataset}/features
      - model.pkl
      - src/evaluate.py
    params:
      - train.state
      - train.split
    outs:
      - evaluation/plots/metrics:
          cache: false
    metrics:
      - evaluation/metrics.json:
          cache: false
    plots:
      - evaluation/plots/sklearn/confusion_matrix.json:
          cache: false
          template: confusion
          x: actual
          y: predicted
