transform:
  datasets:
    seed-vig:
      shape:
        - 17
        - 1600
        - 885
    mi:
      shape: []
featurize:
  level: 3
  wavelet: haar
  threshold: 2.247924
  coefficient_number: -1
train:
  state: 123
  split: 0.75
  svm_kernel: poly
  svm_C: 1
  svm_degree: 3
evaluate:
  state: 123
  split: 0.8
